### ISSUE TITLE
Implementing changes

### ISSUE THREAD

**Issue by Strumwulf** [maxhawkins/drift#3]
after editing and saving changes to the javascript or css files for generating the pages,  is there anything else that needs to be done to see the changes.  I've done a few edits, but I have not seen the changes when I run the program again.

**Comment by maxhawkins** [comment]
Those changes should happen immediately. How are you running the program?

Did you try clearing your browser cache?

**Comment by Strumwulf** [comment]
I'm running the program from the terminal window on my MacbookPro, with the webpages appearing in the Chrome browser.

I'll trying clearing the cache, and seeing if that has any affect.

**Comment by Strumwulf** [comment]
I've cleared the cache, and I'm running drift in safari now.  When I update the css sheet, I do see immediate changes.  but I'm still not able to change text size for the transcript.  

I've attached my app, view and timeline css files.
[drift_css.zip](https://github.com/maxhawkins/drift/files/798071/drift_css.zip)

**Comment by maxhawkins** [comment]
Have you tried editing the page in the Chrome [Web Inspector](https://developers.google.com/web/tools/chrome-devtools/inspect-styles/)? If you open up the page in the inspector you should be able to edit the CSS interactively and see what works.

**Comment by Strumwulf** [comment]
Using the Chrome Web inspector, I can see that font-style is being overwritten by what looks like the font-size value from the TimedText.jsx file.  I've edit the values in the file and refreshed the page but I'm not seeing any changes.  I can edit the values in the inspector, but only on a word by word basis.  I've attached screenshots of the webpage with the inspector running and Javascript file.
[Screenshots.zip](https://github.com/maxhawkins/drift/files/801553/Screenshots.zip)

**Comment by Strumwulf** [comment]
I've figured out the issue.  I need to add the keyword text to my declaration of .word in the timeline.css file.

Thanks for the assistance.
